-- Minimal Supabase-compatible catalog used by the isolated assessment migration test.
create extension if not exists pgcrypto;
do $$ begin create role anon; exception when duplicate_object then null; end $$;
do $$ begin create role authenticated; exception when duplicate_object then null; end $$;
do $$ begin create role service_role; exception when duplicate_object then null; end $$;
create schema auth;
create schema storage;
create schema private;
create table auth.users(id uuid primary key default gen_random_uuid());
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create type public.user_role as enum ('teacher','student');
create table public.profiles(id uuid primary key references auth.users(id), role public.user_role not null, full_name text not null default '');
create table public.student_records(id uuid primary key default gen_random_uuid(), teacher_id uuid not null references public.profiles(id), student_id uuid unique references public.profiles(id), level text not null default 'A1', skills jsonb not null default '{}');
create table public.question_bank(id uuid primary key default gen_random_uuid(), teacher_id uuid not null references public.profiles(id));
create function public.teacher_has_access(target_teacher uuid default auth.uid()) returns boolean language sql stable security definer as $$ select exists(select 1 from public.profiles where id=target_teacher and role='teacher') $$;
create table storage.buckets(id text primary key, name text not null, public boolean not null default false, file_size_limit bigint, allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(), bucket_id text not null references storage.buckets(id), name text not null, owner_id text, unique(bucket_id,name));
alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(regexp_replace(name, '/[^/]*$', ''), '/') $$;
grant usage on schema auth, storage to anon, authenticated, service_role;
grant select, insert, update, delete on storage.objects to authenticated, service_role;
grant select, update on public.profiles, public.student_records, public.question_bank to authenticated;
